//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgenciaViagens.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Viagem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Viagem()
        {
            this.Adquire = new HashSet<Adquire>();
        }
    
        public int id_viag { get; set; }
        public int destino { get; set; }
        public System.DateTime partida { get; set; }
        public System.DateTime chegada { get; set; }
        public decimal vlr_padrao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Adquire> Adquire { get; set; }
        public virtual Destino Destino1 { get; set; }
    }
}